name: movieland
description: A new Flutter project.


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  google_fonts: ^3.0.1
  flashy_tab_bar2: ^0.0.5
  flutter_vector_icons: ^2.0.0
  flutter_svg: ^1.1.6
  http: ^0.13.5
  shimmer: ^2.0.0
  shimmer_animation: ^2.1.0+1
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  

flutter:

  uses-material-design: true


  assets:
    - asstes/
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

